apiVersion: v1
kind: Namespace
metadata:
  name: openspeedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openspeedtest
  name: openspeedtest
  namespace: openspeedtest
spec:
  selector:
    matchLabels:
      app: openspeedtest
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      nodeSelector:
        worker: "true"
      containers:
      - image: openspeedtest/latest:latest
        imagePullPolicy: Always
        name: openspeedtest
        volumeMounts:
        - mountPath: /app/data
          name: openspeedtest-content
      volumes:
      - name: openspeedtest-content
        persistentVolumeClaim:
          claimName: openspeedtest-claim
