kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: code-claim
  namespace: code-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi