kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-claim
  namespace: grafana-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi