---
apiVersion: v1
kind: Namespace
metadata:
  name: arr-stack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: arr-stack
spec:
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      nodeSelector:
        worker: "true"
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
            
          limits: 
            memory: "512Mi"
            cpu: "250m" 
        env:
        - name: prowlarr_Port
          value: "9696"
        ports: 
          - containerPort: 9696
        volumeMounts:
        - mountPath: /app/data
          name: prowlarr-data
      volumes:
      - name: prowlarr-data
        persistentVolumeClaim:
          claimName:  prowlarr-claim
        