kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-claim
  namespace: arr-stack
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi