kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homarr-claim
  namespace: homarr-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi