apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-claim
  namespace: uptime-kuma
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
