kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
